name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout LocalMapFilter
        uses: actions/checkout@v4
        with:
          path: osu-localmap-filter
          fetch-depth: 0

      - name: Checkout osu!
        uses: actions/checkout@v4
        with:
          repository: ppy/osu
          path: osu
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        shell: pwsh
        run: >
          dotnet build
          "$env:GITHUB_WORKSPACE\osu-localmap-filter\osu.Game.Rulesets.LocalMapFilter\osu.Game.Rulesets.LocalMapFilter.csproj"
          -c Release
          --nologo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osu.Game.Rulesets.LocalMapFilter
          path: osu-localmap-filter\osu.Game.Rulesets.LocalMapFilter\bin\Release\net8.0\osu.Game.Rulesets.LocalMapFilter.dll

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: osu.Game.Rulesets.LocalMapFilter
          path: artifact

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifact/osu.Game.Rulesets.LocalMapFilter.dll
